language: rust
rust:
  - stable
addons:
  apt:
    packages:
    - libsdl2-2.0-0
    - libsdl2-dev
    - libsdl2-gfx-dev
    - libsdl2-image-2.0-0
    - libsdl2-image-dev
    - libsdl2-mixer-2.0-0
    - libsdl2-net-2.0-0
    - libsdl2-net-dev
    - libsdl2-ttf-2.0-0
    - libsdl2-ttf-dev
script:
  - rustup component add rustfmt
  - rustup component add clippy
  - cargo fmt --all -- --check
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo clippy
